dist: precise
language: python
install:
    pip install nose coveralls coverage
matrix:
  include:
    - os: osx
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.5-dev
    - os: linux
      python: 3.6
    - os: linux
      python: 3.6-dev
    - os: linux
      python: 3.7-dev
    - os: linux
      python: nightly
    - os: linux
      python: pypy
    - os: linux
      python: pypy3.5-5.8.0
script:
    travis_wait nosetests --with-coverage --cover-package=neat
after_success:
    - if [ -a ".coveralls.yml" ]; then
    	coveralls
        ;
      fi
